backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  repo: https://github.com/dentemple/dentemple.com

publish_mode: editorial_workflow
media_folder: 'static/img' # Media files will be stored in the repo under images/uploads
public_folder: '/img/' # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: data
    label: 'Data'
    folder: data
    identifier_field: name
    extension: json
    create: false
    fields:
      - name: skills
        label: Skills
        widget: 'list'
        fields:
          - name: name
            label: Name
            widget: 'string'
          - name: label
            label: Label
            widget: 'string'
          - name: url
            label: Url
            widget: 'string'
